name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup dotnet '6.0.x'  
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: ./.github/gitversion.yml

      - name: Display dotnet version
        run: dotnet --version

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration release /p:Version=${{ steps.gitversion.outputs.NuGetVersionV2 }} /p:AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }} --no-restore
      
      - name: Push generated package 'Genarator' to GitHub registry
        run: dotnet nuget push ./Generator/bin/Release/*.nupkg  --source "https://nuget.pkg.github.com/paukertj/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}

      - name: Push generated package 'Primitives' to GitHub registry
        run: dotnet nuget push ./Primitives/bin/Release/*.nupkg  --source "https://nuget.pkg.github.com/paukertj/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}

      - name: Push generated package 'Genarator' to nuget.org registry
        run: dotnet nuget push ./Generator/bin/Release/*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }}

      - name: Push generated package 'Primitives' to nuget.org registry
        run: dotnet nuget push ./Primitives/bin/Release/*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }}